version: "3.8"

services:
   server:
     build: ./server
     container_name: server
     ports:
       - "5000:5000"
     env_file:
       - ./server/.env
    
   client:
     build: ./client
     container_name: client
     ports:
       - "5173:5173"
     env_file:
       - ./client/.env
     depends_on:
       - server
